version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: tasks_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - tasks_pgdata:/var/lib/postgresql/data

volumes:
  tasks_pgdata: