server:
  port: 8083

spring:
  application:
    name: task-service
  kafka:
    topic: system-events
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tasks_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_RESOURCE_SERVER_URL:http://localhost:8080/realms/vmeste.tech}

integration:
  services:
    user-service:
      url: ${INTEGRATION_USER_SERVICE_URL:http://localhost:8082}
      name: ${INTEGRATION_USER_SERVICE_NAME:user-service}
    rules-service:
      url: ${INTEGRATION_RULES_SERVICE_URL:http://localhost:8084}
      name: ${INTEGRATION_RULES_SERVICE_NAME:rules-service}